const ActionType = {
    LOAD_USER: 'LOAD_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    PUBLISH_MESSAGE: 'PUBLISH_MESSAGE',
    DISMISS_MESSAGE: 'DISMISS_MESSAGE',
    LOAD_TRIPS: 'LOAD_TRIPS',
    CREATE_TRIP: 'CREATE_TRIP',
    UPDATE_TRIP: 'UPDATE_TRIP',
    REMOVE_TRIP: 'REMOVE_TRIP'
};

export default ActionType;
